
language: python

# https://docs.travis-ci.com/user/languages/python/
#python:
#-   "2.7"
#-   "3.3"
#-   "3.4"

# https://docs.travis-ci.com/user/multi-os/
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
matrix:
    include:
        # Ubuntu 14.04
        -   os: linux
            dist: trusty
            sudo: required
            python: 2.7

install:
-   sudo add-apt-repository -y ppa:deadsnakes/ppa
-   sudo apt-get -yq update
-   sudo apt-get -yq install python3.6 python3.6-dev
-   pip install -r requirements-test.txt

script:
-   set -e
-   ./pep8.sh
-   tox
